name: adhd_project
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.9 <4.0.0"

dependencies:
  audio_service: ^0.18.9
  audio_session: ^0.1.13
  auto_size_text: ^3.0.0
  bloc: ^8.1.2
  bloc_presentation: ^1.0.0
  build_verify: ^3.1.0
  carousel_slider: ^4.2.1
  chopper: ^6.0.0
  chopper_generator: ^6.0.0
  collection: ^1.16.0
  comms: ^1.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_comms: ^1.1.0
  flutter_gen: ^5.0.3
  flutter_hooks: ^0.20.2
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.9
  flutter_portal: ^1.1.4
  flutter_ringtone_player: ^3.2.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.6
  flutter_xlider: ^3.5.0
  freezed_annotation: ^2.1.0
  go_router: ^11.1.2
  http: ^1.0.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  just_audio: ^0.9.31
  leancode_hooks: ^0.0.6
  logging: ^1.0.2
  provider: ^6.0.3
  rxdart: ^0.27.7
  shared_preferences: ^2.0.15
  sleek_circular_slider: ^2.0.1
  stop_watch_timer: ^3.0.2
  table_calendar: ^3.0.9
  timetable:
    git:
      url: git@github.com:JonasWanke/timetable.git
      ref: v1.0.0-alpha.13
  url_launcher: ^6.1.5
  vibration: ^1.8.1

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.2.0
  flutter_gen_runner: ^5.0.3
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  go_router_builder: ^2.0.2
  integration_test:
    sdk: flutter
  json_serializable: ^6.7.1
  leancode_lint: ^6.0.0
  swagger_dart_code_generator: ^2.11.13

flutter:
  uses-material-design: true
  generate: false
  assets:
    - assets/
    - assets/icons/
    - assets/icons/x24/
    - assets/icons/x24/mood/
    - assets/pictures/
    - assets/pictures/light/
    - assets/pictures/dark/
    - assets/fonts/
    - assets/fonts/urbanist/
    - assets/alarms/

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true
